name: so2sat-buildingtype
channels:
  - conda-forge
dependencies:
  - mercantile=1.2.1
  - numpy=1.21.3
  - pandas=1.3.4
  - pillow=8.3.2
  - rasterio=1.2.10
  - requests=2.26.0
  - shapely=1.7.1
  - tqdm=4.62.3
